name: patrika_community_app
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  file_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.1
  haptic_feedback: ^0.5.1+1
  image_picker: ^0.8.4+3
  intl: ^0.19.0
  logger: ^2.4.0
  overlay_support: ^2.1.0
  pinput: ^5.0.0
  provider: ^6.1.2
  pull_to_refresh_flutter3: ^2.0.2
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.1+1
  # todo native splash screen
  smooth_page_indicator: ^1.2.0+3
  toastification: ^2.1.0



dev_dependencies:
  flutter_asset_generator: ^1.2.0
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/